# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://discordapp.com/api/webhooks/697195635572605040/_k3J-BL8KueUPopdCzrCrMqm_eWP7e0q3bs8T1ZuWIqqmtAKYH0HVcI7HB1zFH_nFRdp
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run